#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TF_DIR="$ROOT_DIR/infrastructure/staging-site"
ENV_FILE="${STAGING_ENV_FILE:-$ROOT_DIR/.env.staging.local}"
TFVARS_FILE="$TF_DIR/terraform.tfvars"

if ! command -v terraform >/dev/null 2>&1; then
  echo "Error: terraform is required but was not found in PATH." >&2
  exit 1
fi

if ! command -v aws >/dev/null 2>&1; then
  echo "Error: aws CLI is required but was not found in PATH." >&2
  exit 1
fi

AWS_PROFILE_ARGS=()
if [[ -n "${AWS_PROFILE:-}" ]]; then
  AWS_PROFILE_ARGS=(--profile "$AWS_PROFILE")
fi

aws_cli() {
  aws "${AWS_PROFILE_ARGS[@]}" "$@"
}

CALLER_ACCOUNT_ID="$(aws_cli sts get-caller-identity --query Account --output text)"
CALLER_ARN="$(aws_cli sts get-caller-identity --query Arn --output text)"

DEFAULT_DOMAIN_NAME="${STAGING_DOMAIN_NAME:-rx2solutions-staging.instantbrains.com}"
DEFAULT_HOSTED_ZONE_NAME="${STAGING_HOSTED_ZONE_NAME:-instantbrains.com}"
DEFAULT_BUCKET_NAME="${STAGING_BUCKET_NAME:-${DEFAULT_DOMAIN_NAME//./-}-$CALLER_ACCOUNT_ID}"

echo "Provisioning staging site in AWS account: $CALLER_ACCOUNT_ID"
echo "Using AWS identity: $CALLER_ARN"

if [[ ! -f "$TFVARS_FILE" ]]; then
  cat > "$TFVARS_FILE" <<EOF
aws_region       = "${AWS_REGION:-us-east-1}"
environment      = "staging"
project_prefix   = "${STAGING_PROJECT_PREFIX:-rx2}"
domain_name      = "$DEFAULT_DOMAIN_NAME"
hosted_zone_name = "$DEFAULT_HOSTED_ZONE_NAME"
bucket_name      = "$DEFAULT_BUCKET_NAME"

default_tags = {
  Project   = "rx2solutions"
  ManagedBy = "terraform"
}
EOF
  echo "Created $TFVARS_FILE"
else
  echo "Using existing $TFVARS_FILE"
fi

pushd "$TF_DIR" >/dev/null
terraform init
terraform apply "$@"

BUCKET_NAME="$(terraform output -raw bucket_name)"
DISTRIBUTION_ID="$(terraform output -raw cloudfront_distribution_id)"
AWS_ACCOUNT_ID="$(terraform output -raw aws_account_id)"
STAGING_URL="$(terraform output -raw staging_url)"
popd >/dev/null

AWS_PROFILE_LINE="# AWS_PROFILE=default"
if [[ -n "${AWS_PROFILE:-}" ]]; then
  AWS_PROFILE_LINE="AWS_PROFILE=$AWS_PROFILE"
fi

cat > "$ENV_FILE" <<EOF
# Generated by scripts/provision-staging-site.sh
# Update AWS_PROFILE if you use a named profile in this environment.

STAGING_S3_BUCKET=$BUCKET_NAME
STAGING_CLOUDFRONT_DISTRIBUTION_ID=$DISTRIBUTION_ID
EXPECTED_AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID
STAGING_INVALIDATION_PATHS=/*

# Optional
$AWS_PROFILE_LINE
# STAGING_URL=$STAGING_URL
EOF

echo "Wrote $ENV_FILE"
echo "Staging site URL: $STAGING_URL"